# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/weight_manager?useSSL=false&rewriteBatchedStatements=true
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        enabled: true
        max-active: 10
        min-idle: 5

limiter:
  redis:
    enable: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml