# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        enabled: true
        max-active: 10
