server:
  port: 8080

spring:
  application:
    name: redis-template-demo

  redis:
    host: localhost
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        enabled: true
        max-active: 20
        min-idle: 5