server:
  port: 8080

spring:
  application:
    name: spring-security-demo

  redis:
    host: localhost
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        enabled: true
        max-active: 10
        min-idle: 5