server:
  port: 8080

spring:
  application:
    name: spring-security-demo
#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_admin?useSSL=false&rewriteBatchedStatements=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
      username: root
      password: 12345678
#redis配置
  redis:
    host: localhost
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        enabled: true
        max-active: 10
        min-idle: 5

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml