server:
  port: 8080

spring:
  application:
    name: spring-cache-demo

cache:
  caffeine:
    defaultMaxSize: 50
    defaultDuration: 30
    timeUnit: MINUTES
    specs:
      - cacheName: ORDER_CACHE
        maxSize: 100
        duration: 10
        timeUnit: MINUTES

      - cacheName: USER_CACHE
        maxSize: 200
        duration: 20
        timeUnit: MINUTES
