server:
  port: 8080

spring:
  application:
    name: spring-cache-demo

#redis
  redis:
    host: localhost
    port: 6379
    client-type: lettuce
    lettuce:
      pool:
        enabled: true
        max-active: 20
        min-idle: 5

#cache
cache:
  caffeine:
    defaultMaxSize: 50
    defaultDuration: 30
    timeUnit: MINUTES
    specs:
      - cacheName: ORDER_CACHE
        maxSize: 100
        duration: 10
        timeUnit: MINUTES

      - cacheName: USER_CACHE
        maxSize: 200
        duration: 20
        timeUnit: MINUTES
